### ISSUE TITLE
Hardware details

### ISSUE THREAD

**Issue by meyiao** [facebookresearch/em-pose#3]
Very inspiring work, you guys are awesome!!!
Where can I buy the EM sensors? Or any instructions to diy them?

**Comment by kaufManu** [comment]
Hi,

Thank you for your interest. The sensors that were used for the results in the paper (and the accompanying published data) are currently not available commercially. You could however replace them with similar EM-based sensings systems such as the ones offered by [Polhemus](https://polhemus.com/).

Best regards
Manuel

**Comment by meyiao** [comment]
Thanks for your response, that solves my question.

Best regards!
